services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./src/:/app/
      - ./data/:/data/
      - ./tests/:/app/tests/
      - ./scripts/:/app/scripts/
      - ./requirements-test.txt:/app/requirements-test.txt
    depends_on:
      - db
    environment:
      - FLASK_DEBUG=1
  db:
    image: postgres:11-alpine
    volumes:
      - ./misc/dbdata:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: password
