name: CI tests

on:
  workflow_dispatch:
  pull_request:
    branches: ["master"]

  push:
    branches: ["master"]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for app to be ready..."
          timeout 60 bash -c 'until curl -f http://localhost:5000 > /dev/null 2>&1; do sleep 2; done'
          echo "App is ready!"

      - name: Load test data
        run: |
          echo "Loading test data into database..."
          docker compose exec -T web bash /app/scripts/setup_test_data.sh
          echo "Test data loaded!"

      - name: Install test dependencies in container
        run: docker compose exec -T web pip install -q -r requirements-test.txt

      - name: Run E2E tests in container
        run: docker compose exec -T web sh -c "TEST_BASE_URL=http://localhost:5000 pytest /app/tests/ -v"

      - name: Show logs on failure
        if: failure()
        run: docker compose logs

      - name: Stop services
        if: always()
        run: docker compose down
